name: Build and Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          cat > .env << EOL
          # Server Configuration
          PORT=3000
          NODE_ENV=production

          # Database
          MONGODB_URI="${{ secrets.MONGODB_URI }}"

          # Session
          SESSION_SECRET="${{ secrets.SESSION_SECRET }}"

          # Google OAuth
          GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
          GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
          GOOGLE_CALLBACK_URL="${{ secrets.GOOGLE_CALLBACK_URL }}"
          LOGOUT_REDIRECT_URL="${{ secrets.LOGOUT_REDIRECT_URL || '/' }}"

          # SMS/Notifications
          TELESIGN_CUSTOMER_ID="${{ secrets.TELESIGN_CUSTOMER_ID }}"
          TELESIGN_API_KEY="${{ secrets.TELESIGN_API_KEY }}"

          # AI API
          NEBIUS_API_KEY="${{ secrets.NEBIUS_API_KEY }}"
          DEEPGRAM_API_KEY="${{ secrets.DEEPGRAM_API_KEY }}"
          EOL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fallguardian-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fallguardian-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fallguardian-backend:buildcache,mode=max

      # Set up Azure login - uncomment when ready for Azure deployment
      # - name: Azure login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Container Instances
      #   uses: azure/aci-deploy@v1
      #   with:
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     dns-name-label: fallguardian-backend
      #     image: ${{ secrets.DOCKERHUB_USERNAME }}/fallguardian-backend:latest
      #     registry-login-server: docker.io
      #     registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     name: fallguardian-backend
      #     location: 'eastus'
      #     ports: 3000
      #     environment-variables: |
      #       NODE_ENV=production
      #       PORT=3000
      #     secure-environment-variables: |
      #       MONGODB_URI="${{ secrets.MONGODB_URI }}"
      #       SESSION_SECRET="${{ secrets.SESSION_SECRET }}"
      #       GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
      #       GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
      #       GOOGLE_CALLBACK_URL="${{ secrets.GOOGLE_CALLBACK_URL }}"
      #       TELESIGN_CUSTOMER_ID="${{ secrets.TELESIGN_CUSTOMER_ID }}"
      #       TELESIGN_API_KEY="${{ secrets.TELESIGN_API_KEY }}"
      #       NEBIUS_API_KEY="${{ secrets.NEBIUS_API_KEY }}"
      #       DEEPGRAM_API_KEY="${{ secrets.DEEPGRAM_API_KEY }}"
